# 1. Create a 1D NumPy array containing numbers from 1 to 10
* Question: Use NumPy to create an array with numbers from 1 to 10. Perform the following operations:
    * Find the sum of all elements.
    * Find the mean of the elements.
    * Find the standard deviation of the elements.

In [23]:
import numpy as np

In [24]:
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [25]:
sum_a = np.sum(a)
print(sum_a)

55


In [26]:
mean_a = np.mean(a)
print(mean_a)

5.5


In [27]:
std_a = np.std(a)
print(std_a)

2.8722813232690143


# 2. Indexing in 1D arrays.
* Question: Given the array arr = np.array( [10, 20, 30, 40, 50, 60] ) , perform the following operations:
    * Extract the second and fourth elements.
    * Extract all elements from the third element onwards.
    * Reverse the array using slicing.

In [28]:
arr = np.array([10,20,30,40,50,60])

In [29]:
# second element
print(arr[1])

20


In [30]:
# fourth element
print(arr[3])

40


In [31]:
# from third element
print(arr[2:])

[30 40 50 60]


In [32]:
# reverse
print(arr[::-1])

[60 50 40 30 20 10]


# 3. Reshape a 1D array into a 2D array
* Question: Create a 1D array with 12 elements, ranging from 1 to 12. Reshape it into a 3x4 array.


In [33]:
arr_1d = np.arange(1,13)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [34]:
arr_2d = arr_1d.reshape(3,4)
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# 4. Element - wise operations.
* Question: Given two arrays A = np.array( [1, 2, 3] ) and B = np.array( [4, 5, 6] ), perform the following operations:
    * Add the two arrays.
    * Subtract the second array from the first.
    * Multiply the two arrays element-wise.
    * Divide the first array by the second

In [35]:
A = np.array([1,2,3])
B = np.array([4,5,6])

In [36]:
# Adding.
print(A+B)

[5 7 9]


In [37]:
# Subtract.
print(B-A)

[3 3 3]


In [38]:
# Multiply.
print(A*B)

[ 4 10 18]


In [39]:
# Divide.
print(A/B)

[0.25 0.4  0.5 ]
