# floor, ceil, round, rint

In [ ]:
import numpy as np
a = np.array([[3,4,26,89,23],[3.4,1.1,5.9,10,0.0001]])
print(np.floor(a))

[[ 3.  4. 26. 89. 23.]
 [ 3.  1.  5. 10.  0.]]


In [ ]:
a = np.array([[3,4,26,89,23],[3.4,1.1,5.9,10,0.0001]])
print(np.ceil(a))

[[ 3.  4. 26. 89. 23.]
 [ 4.  2.  6. 10.  1.]]


In [ ]:
a = np.array([[3,4,26,89,23],[3.4,1.1,5.9,10,0.0001]])
print(np.round(a))

[[ 3.  4. 26. 89. 23.]
 [ 3.  1.  6. 10.  0.]]


In [ ]:
a = np.array([[3,4,26,89,23],[3.4,1.1,5.9,10,0.0001]])
print(np.rint(a))

[[ 3.  4. 26. 89. 23.]
 [ 3.  1.  6. 10.  0.]]


# Data Types

In [ ]:
a = np.array([[3,4,26,89,23],[3.4,1.1,5.9,10,0.0001]])
print(a)
print(type(a))

[[3.0e+00 4.0e+00 2.6e+01 8.9e+01 2.3e+01]
 [3.4e+00 1.1e+00 5.9e+00 1.0e+01 1.0e-04]]
<class 'numpy.ndarray'>


In [ ]:
a = np.array([[3,4,26,89,23],[3.4,1.1,5.9,10,0.0001]])
print(a)
print(a.dtype)

[[3.0e+00 4.0e+00 2.6e+01 8.9e+01 2.3e+01]
 [3.4e+00 1.1e+00 5.9e+00 1.0e+01 1.0e-04]]
float64


In [ ]:
a = np.array([[3,4,'26',89,23],[3.4,1.1,5.9,10,0.0001]])
print(a)
print(a.dtype)

[['3' '4' '26' '89' '23']
 ['3.4' '1.1' '5.9' '10' '0.0001']]
<U32


In [ ]:
A = a.astype(float)
print(A)
print(A.dtype)

[[3.0e+00 4.0e+00 2.6e+01 8.9e+01 2.3e+01]
 [3.4e+00 1.1e+00 5.9e+00 1.0e+01 1.0e-04]]
float64


# Dimentional indexing

## One Dimentional indexing

In [ ]:
a = np.array([3.4,1.1,5.9,10,0.0001])
print(a[3])

10.0


## Two Dimentional indexing

In [ ]:
a = np.array([[3,4,'26',89,23],[3.4,1.1,5.9,10,0.0001]])

In [ ]:
print(a[0,2])

26


In [ ]:
print(a[1,4])

0.0001


## Three Dimentional indexing

In [ ]:
a = np.array([[["Marcelo","Benzema","Cristiano","Ozil"],[5,10,7,11]],[[3,4,'26',89],[1.1,5.9,10,0.0001]]])

In [ ]:
print(a[0,0,2])

Cristiano


In [ ]:
a[1,0,1]

'4'

# Slicing

## One DImentional slicing

In [ ]:
a = np.array([3.4,1.1,5.9,10,0.0001])

In [ ]:
print(a[1:4])

[ 1.1  5.9 10. ]


In [ ]:
print(a[:3])

[3.4 1.1 5.9]


## Two Dimentional slicing

In [ ]:
a = np.array([[3,4,'26',89,23],[3.4,1.1,5.9,10,0.0001]])

In [ ]:
print(a[0:2,2:4])

[['26' '89']
 ['5.9' '10']]


In [ ]:
print(a[:,2:])

[['26' '89' '23']
 ['5.9' '10' '0.0001']]


## Third Dimentional slicing

In [ ]:
a = np.array([[["Marcelo","Benzema","Cristiano","Ozil"],[5,10,7,11]],[[3,4,'26',89],[1.1,5.9,10,0.0001]]])

In [ ]:
print(a[0:2,1,1:3])

[['10' '7']
 ['5.9' '10']]


In [ ]:
print(a[:,:,2:4])

[[['Cristiano' 'Ozil']
  ['7' '11']]

 [['26' '89']
  ['10' '0.0001']]]


# Boolean Indexing

In [ ]:
a = np.array([[3,4,26,89,23],[3.4,1.1,5.9,10,0.0001]])

In [ ]:
print(a>15)

[[False False  True  True  True]
 [False False False False False]]


In [ ]:
print(a<10)

[[ True  True False False False]
 [ True  True  True False  True]]


# Fancy Indexing

In [ ]:
a = np.array([[["Marcelo","Benzema","Cristiano","Ozil"],[5,10,7,11]],[[3,4,26,89],[1.1,5.9,10,0.0001]]])

In [ ]:
print(a[[0],[0],[3]])

['Ozil']


In [ ]:
print(a[[0,1],[0,1],[3,1]])

['Ozil' '5.9']


In [ ]:
print(a[[0,1,0],[0,1,0],[3,1,0]])

['Ozil' '5.9' 'Marcelo']
