# Sorting

## One Dimentional Sorting


In [ ]:
a = np.array([3,1,5,10,0])
print(a)

[ 3  1  5 10  0]


In [ ]:
a.sort()
print(a)

[ 0  1  3  5 10]


In [ ]:
b = np.array([3,1,5,10,0])
print(b)

[ 3  1  5 10  0]


In [ ]:
B = np.sort(b)[::-1]
print(B)

[10  5  3  1  0]


## Two Dimentional Sorting


In [ ]:
c = np.array([[3,1,5,10,0],[10,30,3,20,5]])
print(c)

[[ 3  1  5 10  0]
 [10 30  3 20  5]]


In [ ]:
c.sort()
print(c)    # sorted column wise.

[[ 0  1  3  5 10]
 [ 3  5 10 20 30]]


In [ ]:
d = np.array([[3,1,5,10,0],[2,4,1,3,2]])
print(d)

[[ 3  1  5 10  0]
 [ 2  4  1  3  2]]


In [ ]:
d.sort(axis=0)
print(d)    # sorted row wise

[[ 2  1  1  3  0]
 [ 3  4  5 10  2]]


In [ ]:
e = np.array([[3,1,5,10,0],[10,30,3,20,5]])
print(e)

[[ 3  1  5 10  0]
 [10 30  3 20  5]]


In [ ]:
e.sort(axis=1)
print(e)

[[ 0  1  3  5 10]
 [ 3  5 10 20 30]]


## Three Dimentional Sorting

In [ ]:
import numpy as np
f = np.array([[[23,14,78,90],[54,78,12,91]],[[55,66,77,88],[9,35,2,77]]])
print(f)

[[[23 14 78 90]
  [54 78 12 91]]

 [[55 66 77 88]
  [ 9 35  2 77]]]


In [ ]:
f = np.sort(f,axis=0)   # Sort between layers
print(f)

[[[23 14 77 88]
  [ 9 35  2 77]]

 [[55 66 78 90]
  [54 78 12 91]]]


In [ ]:
f = np.array([[[23,14,78,90],[54,78,12,91]],[[55,66,77,88],[9,35,2,77]]])
print(f)

[[[23 14 78 90]
  [54 78 12 91]]

 [[55 66 77 88]
  [ 9 35  2 77]]]


In [ ]:
f = np.sort(f,axis=1)   # sort between rows in each layer
print(f)

[[[23 14 12 90]
  [54 78 78 91]]

 [[ 9 35  2 77]
  [55 66 77 88]]]


# Copy and View

In [ ]:
# Creating a simple 1D array
g = np.array([33,44,55,66,77])
print(g)

[33 44 55 66 77]


In [ ]:
# Creating some copies of that array
x = g
y = g.view()    # shallow copy
z = g.copy()    # deep copy

In [ ]:
print(x)
print(y)
print(z)

[33 44 55 66 77]
[33 44 55 66 77]
[33 44 55 66 77]


In [ ]:
# Changing a value of the main array
g[1] = 100

In [ ]:
print(x)
print(y)
print(z)

[ 33 100  55  66  77]
[ 33 100  55  66  77]
[33 44 55 66 77]


# Reshape and Resize

In [ ]:
a = np.arange(16)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
print(a.shape)

(16,)


In [ ]:
b = a.reshape(2,8)
print(b)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [ ]:
c = a.reshape(8,2)
print(c)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [ ]:
d = a.reshape(4,4)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
e = a.reshape(4,5)

ValueError: cannot reshape array of size 16 into shape (4,5)

In [ ]:
# but
a = np.arange(16)
a.resize(4,10)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]


# Flatten

In [ ]:
a = np.array([[10,20,30],[15,25,35]])
print(a)

[[10 20 30]
 [15 25 35]]


In [ ]:
b = a.flatten()
print(b)

[10 20 30 15 25 35]


# Dot Product

## In Two Dimention

In [ ]:
a = np.array([[2,3,4],[5,6,7]])
b = np.array([[10,20,30],[8,7,6],[3,2,1]])

In [ ]:
ab = np.dot(a,b)

In [ ]:
print("a =\n",a)
print("\nb =\n",b)
print("\nab =\n",ab)

a =
 [[2 3 4]
 [5 6 7]]

b =
 [[10 20 30]
 [ 8  7  6]
 [ 3  2  1]]

ab =
 [[ 56  69  82]
 [119 156 193]]


## In Three Dimentional

In [ ]:
c = np.array([[[2,1,3],[4,5,3]],[[3,8,2],[5,6,4]]])
d = np.array([[[5,1,9],[3,3,4],[9,0,1]],[[6,3,4],[8,1,2],[0,7,6]]])

In [ ]:
cd = np.dot(c,d)

In [ ]:
print("c =\n",c)
print("\nd =\n",d)
print("\ncd =\n",cd)

c =
 [[[2 1 3]
  [4 5 3]]

 [[3 8 2]
  [5 6 4]]]

d =
 [[[5 1 9]
  [3 3 4]
  [9 0 1]]

 [[6 3 4]
  [8 1 2]
  [0 7 6]]]

cd =
 [[[[40  5 25]
   [20 28 28]]

  [[62 19 59]
   [64 38 44]]]


 [[[57 27 61]
   [82 31 40]]

  [[79 23 73]
   [78 49 56]]]]


# Sorting in Axis 0,1,2

## Minimum

In [ ]:
a = np.array([[[2,3,4],[6,1,3]],[[5,8,3],[5,3,1]]])
print(np.min(a))    # This will display the minimum from the all elements.

1


In [ ]:
a = np.array([[[2,3,4],[6,1,3]],[[5,8,3],[5,3,1]]])
print(a,"\n\n")
print("Sorted\n",np.min(a,axis=0)) # Layer wise sorting.

[[[2 3 4]
  [6 1 3]]

 [[5 8 3]
  [5 3 1]]] 


Sorted
 [[2 3 3]
 [5 1 1]]


In [ ]:
a = np.array([[[2,3,4],[6,1,3]],[[5,8,3],[5,3,1]]])
print(a,"\n\n")
print("Sorted\n",np.min(a,axis=1)) # Column wise sorting.

[[[2 3 4]
  [6 1 3]]

 [[5 8 3]
  [5 3 1]]] 


Sorted
 [[2 1 3]
 [5 3 1]]


In [ ]:
a = np.array([[[2,3,4],[6,1,3]],[[5,8,3],[5,3,1]]])
print(a,"\n\n")
print("Sorted\n",np.min(a,axis=2)) # Row wise sorting.

[[[2 3 4]
  [6 1 3]]

 [[5 8 3]
  [5 3 1]]] 


Sorted
 [[2 1]
 [3 1]]


## Maximum

In [ ]:
a = np.array([[[2,3,4],[6,1,3]],[[5,8,3],[5,3,1]]])
print(np.max(a))    # This will display the maximum from the all elements.

8


In [ ]:
a = np.array([[[2,3,4],[6,1,3]],[[5,8,3],[5,3,1]]])
print(a,"\n\n")
print("Sorted\n",np.max(a,axis=0)) # Layer wise sorting.

[[[2 3 4]
  [6 1 3]]

 [[5 8 3]
  [5 3 1]]] 


Sorted
 [[5 8 4]
 [6 3 3]]


In [ ]:
a = np.array([[[2,3,4],[6,1,3]],[[5,8,3],[5,3,1]]])
print(a,"\n\n")
print("Sorted\n",np.max(a,axis=1)) # Column wise sorting.

[[[2 3 4]
  [6 1 3]]

 [[5 8 3]
  [5 3 1]]] 


Sorted
 [[6 3 4]
 [5 8 3]]


In [ ]:
a = np.array([[[2,3,4],[6,1,3]],[[5,8,3],[5,3,1]]])
print(a,"\n\n")
print("Sorted\n",np.max(a,axis=2)) # Row wise sorting.

[[[2 3 4]
  [6 1 3]]

 [[5 8 3]
  [5 3 1]]] 


Sorted
 [[4 6]
 [8 5]]


## Median

In [ ]:
a = np.array([[[2,3,4],[6,1,3]],[[5,8,3],[5,3,1]]])
print(np.median(a))    # This will display the median from the all elements.

3.0


In [ ]:
a = np.array([[[2,3,4],[6,1,3]],[[5,8,3],[5,3,1]]])
print(a,"\n\n")
print("Sorted\n",np.median(a,axis=0)) # Layer wise median calculation.

[[[2 3 4]
  [6 1 3]]

 [[5 8 3]
  [5 3 1]]] 


Sorted
 [[3.5 5.5 3.5]
 [5.5 2.  2. ]]


In [ ]:
a = np.array([[[2,3,4],[6,1,3]],[[5,8,3],[5,3,1]]])
print(a,"\n\n")
print("Sorted\n",np.median(a,axis=1)) # Column wise median calculation.

[[[2 3 4]
  [6 1 3]]

 [[5 8 3]
  [5 3 1]]] 


Sorted
 [[4.  2.  3.5]
 [5.  5.5 2. ]]


In [ ]:
a = np.array([[[2,3,4],[6,1,3]],[[5,8,3],[5,3,1]]])
print(a,"\n\n")
print("Sorted\n",np.median(a,axis=2)) # Row wise median calculation.

[[[2 3 4]
  [6 1 3]]

 [[5 8 3]
  [5 3 1]]] 


Sorted
 [[3. 3.]
 [5. 3.]]
