* Class name of NumPy is ndarray.
* NumPy is a Python library used for working with arrays.
* In Python, we have lists, that serves the purpose Of arrays. But they are slow to process.
* NumPy aims to provide an array object that is up to faster than
traditional Python lists.
* The array object in NumPy is called ndarray. It provides a lot of supporting functions that make working with ndarray very easy.
* Arrays are very frequently used in data science. Where speed and resources are very important.
* Collection of homogenous data.
* It does not support hetrogenous data.

In [ ]:
import numpy as np
x = np.ndarray([3,2,4])
print(x)

[[[-0.25 -0.5   0.   -0.25]
  [ 0.25 -0.5   0.5  -0.25]]

 [[ 0.25  0.    0.5   0.25]
  [ 0.25  0.5   0.    0.25]]

 [[-0.25  0.5  -0.5   0.25]
  [-0.25  0.   -0.5  -0.25]]]


In [ ]:
x = np.array([9,4,7])
print(x)

[9 4 7]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
# dimention of x
x.ndim

1

In [ ]:
# shape of x
x.shape

(3,)

In [ ]:
# 2D array
a = np.array([[2,4,5,6],[9,8,7,6]])
print(a)

[[2 4 5 6]
 [9 8 7 6]]


In [ ]:
# of shape (4,5)
b = np.array([[44,33,22,11,55],[10,20,30,40,50],[94,56,90,11,90],[-1,-2,-3,-4,0]])
print(b)
print(np.shape(b))

[[44 33 22 11 55]
 [10 20 30 40 50]
 [94 56 90 11 90]
 [-1 -2 -3 -4  0]]
(4, 5)


In [ ]:
# of shape (2,6)
c = np.array([[6,12,18,24,30,36],[5,10,15,20,25,30]])
print(c)
print(np.shape(c))

[[ 6 12 18 24 30 36]
 [ 5 10 15 20 25 30]]
(2, 6)


In [ ]:
d = np.array([[[2,4,5],[7,17,30]],[[2,4,5],[7,17,30]]])
print(d)
print(np.shape(d))
print(np.ndim(d))

[[[ 2  4  5]
  [ 7 17 30]]

 [[ 2  4  5]
  [ 7 17 30]]]
(2, 2, 3)
3


In [ ]:
# (2,4,2)
e = np.array([[[1,2],[2,4],[3,6],[4,8]],[[5,10],[6,12],[7,14],[8,16]]])
print(np.ndim(e))
print(np.shape(e),"\n")

# (3,2,3)
f = np.array([[[1,2,3],[2,3,4]],[[3,4,5],[4,5,6]],[[5,6,7],[6,7,8]]])
print(np.ndim(f))
print(np.shape(f),"\n")

# (4,2,2)
g = np.array([[[100,50],[90,45]],[[1000,500],[32,16]],[[50,25],[12,6]],[[3,1.5],[8,4]]])
print(np.ndim(g))
print(np.shape(g))

3
(2, 4, 2) 

3
(3, 2, 3) 

3
(4, 2, 2)


In [ ]:
print(np.zeros((2,3,4)))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
print(np.zeros((2,3,4),dtype = int))

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [ ]:
print(np.ones((3,2,8),dtype = int))

[[[1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]]]


In [ ]:
print(np.linspace(0,10,3))
np.linspace?

[ 0.  5. 10.]


In [ ]:
np.linspace(0,80)

array([ 0.        ,  1.63265306,  3.26530612,  4.89795918,  6.53061224,
        8.16326531,  9.79591837, 11.42857143, 13.06122449, 14.69387755,
       16.32653061, 17.95918367, 19.59183673, 21.2244898 , 22.85714286,
       24.48979592, 26.12244898, 27.75510204, 29.3877551 , 31.02040816,
       32.65306122, 34.28571429, 35.91836735, 37.55102041, 39.18367347,
       40.81632653, 42.44897959, 44.08163265, 45.71428571, 47.34693878,
       48.97959184, 50.6122449 , 52.24489796, 53.87755102, 55.51020408,
       57.14285714, 58.7755102 , 60.40816327, 62.04081633, 63.67346939,
       65.30612245, 66.93877551, 68.57142857, 70.20408163, 71.83673469,
       73.46938776, 75.10204082, 76.73469388, 78.36734694, 80.        ])

In [ ]:
print(np.full((3,4),77,float))

[[77. 77. 77. 77.]
 [77. 77. 77. 77.]
 [77. 77. 77. 77.]]


In [ ]:
print(np.eye(2,2))

[[1. 0.]
 [0. 1.]]


In [ ]:
np.random.random?
print(np.random.random((3,2,2)))

[[[0.87104695 0.56542479]
  [0.6400181  0.46221048]]

 [[0.32452034 0.15460187]
  [0.05206981 0.91338029]]

 [[0.18746858 0.40930428]
  [0.56682442 0.92162982]]]


In [ ]:
np.random.randint?
print(np.random.randint(20,50,(2,2)))

[[42 32]
 [36 43]]


In [ ]:
print(np.random.randint(20,30,(3,2)))

[[24 22]
 [22 27]
 [29 21]]


In [ ]:
a = np.array([[4,3,2],[1,5,7]])
b = np.array([[8,1,3],[1,4,2]])
print(a,"\n\n",b)

[[4 3 2]
 [1 5 7]] 

 [[8 1 3]
 [1 4 2]]


In [ ]:
print(np.add(a,b))

[[12  4  5]
 [ 2  9  9]]


In [ ]:
print(np.subtract(b,a))

[[ 4 -2  1]
 [ 0 -1 -5]]


In [ ]:
print(np.multiply(a,b))

[[32  3  6]
 [ 1 20 14]]


In [ ]:
print(np.divide(a,b))

[[0.5        3.         0.66666667]
 [1.         1.25       3.5       ]]


In [ ]:
print(np.power(a,b))

[[65536     3     8]
 [    1   625    49]]
